apiVersion: v2
name: hedgedoc
description: HedgeDoc (formerly known as CodiMD) is an open-source, web-based, self-hosted, collaborative markdown editor
type: application
version: 0.0.0
appVersion: 1.11.0

keywords:
  - editor
  - markdown
  - real-time
  - notes
  - collaboration
  - diagrams
  - hedgedoc
  - hackmd
  - codimd
home: https://hedgedoc.org/
sources:
  - https://github.com/RobertoBochet/hedgedoc-chart
  - https://github.com/hedgedoc/hedgedoc
  - https://quay.io/repository/hedgedoc/hedgedoc
maintainers:
  - name: Marco Costanzo
    email: marcosti096@duck.com
  - name: Roberto Bochet
    email: r@robertobochet.me

icon: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbDpzcGFjZT0icHJlc2VydmUiIGZpbGwtcnVsZT0iZXZlbm9kZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgc3Ryb2tlLW1pdGVybGltaXQ9IjIiIGNsaXAtcnVsZT0iZXZlbm9kZCIgdmlld0JveD0iMCAwIDE3NzIgMTc3MiI+PGcgZmlsbC1ydWxlPSJub256ZXJvIj48cGF0aCBmaWxsPSIjYjUxZjA4IiBkPSJtMTU1My43IDk2MSA3NS4yLTc1LjItNzUuMi03NS4yIDU2LjYtOTAuMS05MC4xLTU2LjYgMzUuMS0xMDAuNS0xMDAuNC0zNS4xIDExLjktMTA1LjgtMTA1LjgtMTEuOS0xMS45LTEwNS43LTEwNS43IDExLjktMzUuMi0xMDAuNS0xMDAuNCAzNS4yLTU2LjYtOTAuMUw5NjEgMjE4bC03NS4zLTc1LjItNzUuMiA3NS4yLTkwLjEtNTYuNi01Ni42IDkwLTEwMC41LTM1LTM1LjEgMTAwLjQtMTA1LjgtMTItMTEuOSAxMDUuOC0xMDUuNyAxMiAxMS45IDEwNS43LTEwMC41IDM1LjEgMzUuMiAxMDAuNC05MC4xIDU2LjcgNTYuNiA5MC03NS4yIDc1LjMgNzUuMiA3NS4zLTU2LjYgOTAgOTAgNTYuNy0zNSAxMDAuNCAxMDAuNCAzNS4yLTEyIDEwNS43IDEwNS44IDEyIDEyIDEwNS43IDEwNS43LTEyIDM1LjEgMTAwLjUgMTAwLjUtMzUuMSA1Ni42IDkwIDkwLTU2LjUgNzUuMyA3NC41IDc1LjMtNzQuNSA5MCA1Ni42IDU2LjctOTAuMSAxMDAuNCAzNS4xIDM1LjItMTAwLjQgMTA1LjcgMTEuOSAxMi0xMDUuOCAxMDUuNy0xMS45LTEyLTEwNS43IDEwMC41LTM1LjItMzUuMS0xMDAuNCA5MC01Ni42LTU2LjUtOTAuMVoiLz48cGF0aCBmaWxsPSIjZmNjYThjIiBkPSJNMTQwMS4zIDEwMDQuOGEyNjMuMyAyNjMuMyAwIDAgMC00NDguNi0xODcuMWwtNjcuMSA2Ny01NC45LTU0LjhhMjYzLjMgMjYzLjMgMCAxIDAtMzc3LjcgMzY2bDQzMi44IDQzMi41IDQyMy4zLTQyMy41YzUyLjgtNDkuOCA5Mi4yLTEyMCA5Mi4yLTIwMC4xIi8+PHBhdGggZmlsbD0idXJsKCNhKSIgZD0iTTg4NS42IDg4NC43IDgzMC43IDgzMGEyNjMuMyAyNjMuMyAwIDEgMC0zNzcuNyAzNjZsNDMyLjggNDMyLjUiLz48L2c+PGcgZmlsbC1ydWxlPSJub256ZXJvIj48cGF0aCBmaWxsPSIjMDEwMDA3IiBkPSJNOTYxIDE1NTMuNmExMDYgMTA2IDAgMCAwLTE1MC42IDAgNzUuMyA3NS4zIDAgMCAwIDE1MC42IDBNNzk3LjcgMTA5OC4yYTU3LjYgNTcuNiAwIDEgMS0xMTUuMSAwIDU3LjYgNTcuNiAwIDAgMSAxMTUuMSAwIi8+PHBhdGggZmlsbD0iI2ZmZmZmYSIgZD0iTTc3OCAxMDg5LjZhMTYgMTYgMCAxIDEtMzIgMCAxNiAxNiAwIDAgMSAzMiAwIi8+PHBhdGggZmlsbD0iIzAxMDAwNyIgZD0iTTEwODkuNyAxMDk4LjJhNTcuNiA1Ny42IDAgMSAxLTExNS4yIDAgNTcuNiA1Ny42IDAgMCAxIDExNS4yIDAiLz48cGF0aCBmaWxsPSIjZmZmZmZhIiBkPSJNMTA2OS45IDEwODkuNmExNiAxNiAwIDEgMS0zMS45IDAgMTYgMTYgMCAwIDEgMzEuOSAwIi8+PC9nPjxkZWZzPjxsaW5lYXJHcmFkaWVudCBpZD0iYSIgeDE9IjAiIHgyPSIxIiB5MT0iMCIgeTI9IjAiIGdyYWRpZW50VHJhbnNmb3JtPSJtYXRyaXgoMjAwIC00MjAgNDIwIDIwMCA2NjAgMTM0MCkiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBvZmZzZXQ9IjAiIHN0b3AtY29sb3I9IiNmY2NhOGMiLz48c3RvcCBvZmZzZXQ9IjEiIHN0b3AtY29sb3I9IiNkY2EwNTUiLz48L2xpbmVhckdyYWRpZW50PjwvZGVmcz48L3N2Zz4=
